yropert/startour

.gitignore, Gemfile, Gemfile.lock, app/models/booking.rb, app/models/ship.rb, app/models/user.rb, app/uploaders/photo_uploader.rb, db/seeds.rb
Collaborators added to database.
Each member has its own ship.
=> Seeds added to the db

app/controllers/ships_controller.rb, app/views/ships/index.html.erb, app/views/ships/show.html.erb, test/controllers/ships_controller_test.rb
Added a ship controller and views
Right now, working on ships show view
=> finished ship view,controller

app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_footers.scss, app/assets/stylesheets/components/_index.scss, app/views/pages/home.html.erb
=> Homepagescss

app/views/layouts/application.html.erb, app/views/pages/home.html.erb, app/views/shared/_footer.html.erb, app/views/ships/index.html.erb, app/views/ships/show.html.erb
yo tio 
I finished adding the partial footer and added the background to the ships show page
hasta luego
=> Ship controller

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_secondcontainer.scss, app/assets/stylesheets/components/_thirdcontainer.scss, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb
margin fait pour la page sign up et log in! attention page log in ne pas modifier le margin
=> Frontformdevise

app/assets/stylesheets/components/_banner-show.scss, app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_index.scss, app/views/ships/show.html.erb
the ship show view is presentable as i finished the banner, and the footer
=> finished the show page for ships including the button and footer

app/controllers/bookings_controller.rb, app/controllers/ships_controller.rb, app/views/bookings/new.html.erb, db/migrate/20191113110023_add_default_value_to_bookings_status.rb, db/migrate/20191113112129_change_date_data_type_on_bookings.rb, db/schema.rb, test/controllers/bookings_controller_test.rb
we have started the booking controller and show page. we need to finish the show page
=> booking show and controller started and functional

app/views/bookings/new.html.erb
front sur le formulaire pour créer une réservation opérationnel
=> front sur formulaire booking user fait

app/controllers/owner/bookings_controller.rb, app/views/owner/bookings/index.html.erb, test/controllers/owner/bookings_controller_test.rb
started the owner view and and controller
=>  started owner controller and view

app/controllers/ships_controller.rb, app/models/ship.rb, app/models/user.rb, app/views/layouts/application.html.erb, app/views/shared/_footer.html.erb, app/views/ships/_form.html.erb, app/views/ships/new.html.erb, app/views/ships/show.html.erb
Ships#new controller actions (new & create) are working.
Ships#new view is live.
=> Ships new view

app/assets/stylesheets/components/_4thcontainer.scss, app/assets/stylesheets/components/_index.scss, app/views/owner/bookings/index.html.erb
Front basique (texte) fait, en attente de données pour compléter et baisser le footer
=> front basique fait en partie

app/assets/stylesheets/components/_card.scss
mise en forme légère des cars trip
=> mise en forme des cards trips

db/seeds.rb
Avatars are now fully implemanted
=> fix avatar with remote-url

app/controllers/owner/bookings_controller.rb, app/views/owner/bookings/index.html.erb
finished some small updates to the controller
=> small updates

app/assets/stylesheets/components/_card.scss, app/controllers/owner/ships_controller.rb, app/views/layouts/application.html.erb, app/views/owner/ships/index.html.erb, test/controllers/owner/ships_controller_test.rb
ajout view owner ships, et ajout du button renvoyant sur la view ships
=> view owner ships et button

app/assets/stylesheets/components/_ownerbookingcolor.scss, app/controllers/owner/bookings_controller.rb, app/views/owner/bookings/index.html.erb
need someone to review my  error message. It shows up on the page but because it needs CSS you can only see it when its highlighted.
=> error message in place need front end

app/controllers/ships_controller.rb, app/javascript/packs/application.js, app/javascript/plugins/init_mapbox.js, app/models/ship.rb, app/views/ships/show.html.erb, config/initializers/geocoder.rb, db/migrate/20191114104838_add_coordinates_to_ships.rb, db/schema.rb, package.json, yarn.lock
ajout de la map dans ship/show.
ajout de latitude et longitude sur la table ships
ajout de gem.
attention faire un db:migrate !
=> add map in show

app/controllers/owner/bookings_controller.rb, app/views/owner/bookings/index.html.erb
completed the buttons to redirect on the owners page but we need to do the front
=>  completed buttons to redirect on owners page

app/assets/stylesheets/components/_background.scss, app/assets/stylesheets/components/_banner-show.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_ecriture.scss, app/assets/stylesheets/pages/_home.scss, app/views/layouts/application.html.erb, app/views/ships/index.html.erb
front homepage entièrement refait, à tester avec toutes les seeds refaite pour voir le rendu final
=> Front home

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_ecriture.scss, app/assets/stylesheets/components/_ownerbookingcolor.scss, app/views/owner/bookings/index.html.erb
added product cards and the  accept or decline button
=> created product cards for owner page

app/controllers/ships_controller.rb
removed the ability for a user to view their own ships
=> completed removing users ship

app/controllers/bookings_controller.rb, app/views/bookings/new.html.erb, db/seeds.rb
=> bookings#new form, content updated

app/controllers/ships_controller.rb, app/views/owner/ships/index.html.erb, app/views/ships/_eform.html.erb, app/views/ships/edit.html.erb, config/routes.rb
Edit action was missing.
So the route and the view as well
=> edit action, route and view

app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb
placeholders have been added to sign up page
=> inserted placeholders

app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_card.scss, app/assets/stylesheets/components/_ecriture.scss, app/views/owner/ships/index.html.erb
front des cards fait, revoir peut etre (si y'a le temps) la position du prix en fonction de la longueur du nom du vaisseau (risque de conflit au niveau des div..)
=> front des cards myships, revoir position du prix a la fin?

app/assets/stylesheets/components/_ecriture.scss, app/views/owner/bookings/index.html.erb
Le texte apparaissant si "my bookings" est vide a été stylisé
=> front texte si espace vide

app/assets/stylesheets/components/_navbar.scss, app/views/shared/_navbar.html.erb
navbar changement de couleur de text 
ajout d'un bouton vers bookings
=> navbar changement de couleur de text et ajout de fonction bookings

app/javascript/plugins/init_mapbox.js
=> change color map

app/assets/stylesheets/components/_banner-show.scss, app/assets/stylesheets/components/_button.scss, app/assets/stylesheets/components/_card.scss, app/views/owner/ships/index.html.erb, app/views/ships/show.html.erb
Front de la show fait.
Ajout du bouton Back est-il nécessaire????
=> Show front end

app/controllers/bookings_controller.rb, app/models/booking.rb, app/views/bookings/index.html.erb, app/views/bookings/new.html.erb, db/migrate/20191115134830_remove_captain_from_ships.rb, db/schema.rb
Total price math is set up (with or without captain)
Removed captain to Ships table
=> Bookings index

app/controllers/bookings_controller.rb, app/views/ships/_form.html.erb, db/seeds.rb
Ships seeds without captain to display them in index
Booking's total price is now removed from the booking#new form
=> fixed seeds and booking#new
